### ISSUE TITLE
Threads safety tests

### ISSUE THREAD

**Issue by asd-and-Rizzo** [ashmind/net-feature-tests#23]
Some containers are not thread safe. E.g. Unity container is thread unsafe for registration, but safe for resolve. Search "unity container thread safe".

Different containers throw different errors, may be some silently eat concurrency errors. E.g. possible error is "Collection was modified; enumeration operation may not execute". I see these while running my patch https://github.com/danielpalme/IocPerformance/pull/50 with Multi mode.

I think this important feature to document cause can lead to some errors, not sure how to create all such tests. At leasy this can be manually documented, just need some start point to commit changes.

**Comment by ashmind** [comment]
It's a good idea, and I've considered it before, but I don't see how this can be tested reliably. It is often possible to prove a concurrency issue by repeating parallel tests enough, but passing tests don't really prove there is no issues.

And given that the whole thing is strongly test-based, there is no good choice for manual documentation at the moment -- I am not sure how maintainable that would be anyway. New library versions can resolve  previous issues, but also introduce new ones.

Something like [Microsoft Chess](http://research.microsoft.com/en-us/projects/chess/) could be useful, but I am not aware of any actively maintained projects that attempt to do the same thing.

**Comment by asd-and-Rizzo** [comment]
If tests ever show error then there is concurrency issue. If tests do not show error - undefined, but probably safe. So can get half of answer for sure, other half is probable. This can be automated.

**Comment by dotnetjunkie** [comment]
IMO doing such a test that verifies whether eregistrations can be safely made in a multi-threaded environment, doesn't make any sense at all, because attempting to alter the configuration when running a multi-threaded application would lead to very un-deterministic behavior, even if the container itself is thread-safe.

For this exact reason Simple Injector blocks this and the reason why this never works is explained here: https://simpleinjector.readthedocs.org/en/latest/decisions.html#the-container-is-locked-after-the-first-call-to-resolve.

So my even trying to test this (which is really hard and indeterministic with an automated test) communicates IMO the wrong message.

**Comment by asd-and-Rizzo** [comment]
I work at project being  3+ years(and ongoing) which did exactly that - several registrations and resolution on start up time into Unity container with custom lock layer above to make registration safe. This was needed because we had system of concurrently loaded feature parts(plugins) which did resolutions of common infrastructure items which where registered first and did registrations of new items on start.  Resolutions are needed to resolve settings depending on which features parts registered new items(e.g. if features are on/off, authentication on/off). After all this done, functional modules/add-ins where concurrently loaded and used provided registrations, these where given with child containers. This was made as part of optimization of MS Office add-in suite start, so all non UI initialization and IO was offloaded into several .NET Tasks.

If thread unsafe container locked on first resolution in our case?
1. Create initial container
2. Create several child
3. Create new container copying initial + child registrations into new one. Complex one.
Not so good.

I can imagine high availability application with demand of hot swapping on configurations change which cannot afford stand by time or memory consumption overhead of AppDomains as unit of isolation. Here change in config could lead to change in container leading to new calls to it resolve new items when container works as factory. There are containers which seems for this (MEF, OSGi), Unity seems possible with this. If container is freeze after resolution I have to invent yet another workaround for feature which should be part of container features. 

Actually in project I mentioned we already have several 3rd party and ad-hoc containers, and mix of 3rd party and ad-hoc  plugins/add-ins(with DI container or AppDomain or Process isolation levels). So having container which thread unsafe and closed upon first resolution is another force to do more ad-hoc.

But more of this, there https://bitbucket.org/dadhi/dryioc which claims to be thread safe and measured to be very fast, and at the same time is feature rich. May be it can do some GC pressure if I do concurrent registration and resolutions, but I have option to refactor my code instead to be forced into some "right" design. So "Fast by default" not so directly related with container freeze or thread safety. 

Yet another point for container be freeze after first resolution and do not care of concurrent - allow using container on devices(.NET Micro, .NET CF,Xamarin iOS) via compile out container into code. But  this is matter of refactoring for devices guided by policy.

Actually example with singleton  `ILogger` may be default (`if null` comparison overhead) but provided with `DoubleRegistrationPolicy:IPolicy`  hook for those who needs other behaviour.

What I want to say that it is up developers to choose `right` design and container and right speed, guided by features comparison given.

**Comment by asd-and-Rizzo** [comment]
Seems I made tests wrong (i.e. error raised on registering `IDummyTwo` multiple times e.g. `A mapping for interface of type IDummyTwo already exists.  MicroSliver does not allow for multiple bindings of the same type`). Seems need to make tests specific for threading, cause only some errors where of that (e.g. `Collection was modified; enumeration operation may not execute.`) avoiding 2 times same service and checking registrations counts instead of relying just on error.

**Comment by dotnetjunkie** [comment]
I think you misunderstood my comment. Any DI container that is not thread-safe to resolve from is almost completely useless in for most of application types we create in .NET. Simple Injector is thread-safe as well and if you read [the link](https://simpleinjector.readthedocs.org/en/latest/decisions.html#the-container-is-locked-after-the-first-call-to-resolve) closely, you will see that there are actually multiple ways to add new registrations at a later point in time. The explicit limitation however is that you can't do this by calling the Register overloads after the container is used for resolving. As the document explains, the main reason for this limitation is not for performance, but for correctness.

**Comment by asd-and-Rizzo** [comment]
I was not read to end point cause treated "lock" as real final lock., did now.

Actually for most of "the link" text I can argue with propositions how things could be different and yet performant and correct. I never wrote production container or did all architecture styles on .NET. Right now seems that "the link" tries to limit container implementation to some architectures/domains specific cases, while these decision can be delayed to be decided by end user, while providing ways to define behavior policies, good tracing and diagnostics, allowing to get OutOfMemoryException if to Register/Resolve million times, and do restriction with looks like FxCop  addins or [TestFixture] with Mono.Cecil over bin and fail if Register used anywhere except one class.

One of these to make container immutable after first resolve.
E.g. problem with logger:
```
var c = new Container();
c
.RegisterTransient<ILogger,Logger>()
.RegisterSingleton<IUseLogger,UseLogger>();
var u1 = c.Resolve<IUseLogger>();//Logger
var c2 = c.RegisterTransient<ILogger,FileLogger>();
var u2 = c.Resolve<IUseLogger>(); //FileLogger
var u3  = c.Resolve<IUseLogger>();//Logger
Assert.IsTrue(u3==u1);
Assert.IsTrue(u2! = u3 );
Assert.IsTrue(u2! = u1 );
```
With web request
"""
class Handler(IContainer c):IHandler{
void Before()
{
    if (c.Resolve<ICache>().GetValue(...))..
}

void After()
{ 
    // some other thread does myC.Register<ICache,MyCache>() does not influences next line cause container is immutalbe
    if (c.Resolve<ICache>().SetValue(...))..
}

}

var h = c.Resolve<IHandler>();
h.Before();
var scope = c.RegisterScoped<ICache,NewCache>();
h.After(); // still used old cache
scope.Dispose()
h.After(); // still used old cache
````

Same immutability may be applied to Func<ICache> used as factory.

Apply, "allowing to get OutOfMemoryException if to Register/Resolve million times, and do restriction with looks like FxCop  addins or [TestFixture] with Mono.Cecil over bin and fail if Register used anywhere except one class."

"Container instance per AppDomain" is also not so default as it may seems. Fully containered applications allows for more fine grained isolation than AppDomains and allow sharing much more resources/shared registration than 10 AppDomains in one Process do.

So there is still room for tests
1. All container considered are thread safe to Resolve.
2. What if I will Register in several threads? We had such scenario in real application I mentioned.
3. What containers allow to Register after BuildContainer or first Resolve? If allow, then if concurrent Register/Resolve is thread safe?

**Comment by ashmind** [comment]
Thanks for the detailed discussion.

1. I think there is definitely room for tests around Resolve, but I don't see a way to do it deterministically at the moment. Even if I run the test thousands of times in parallel, there is always a chance that race condition wouldn't be hit -- and I want to avoid overly long tests as well.

2. I think there is value in having Register as thread-safe as well. Even if container is frozen after registration, it doesn't mean the registration itself can't be multithreaded for one reason or another (e.g. async loading of some component list from a disk). It is not a critical feature though. Same test concern applies here though.

3. I feel that simultaneous Register/Resolve is an edge case and shouldn't be recommended since resolutions become unpredictable.

**Comment by dotnetjunkie** [comment]
You can't reasonably test whether registration is thread-safe or not:
* As Andrey already said, these tests are not deterministic. They might fail once in a 10,000 times, but even if they never fail, this doesn't mean that registration is thread-safe. It only means that your test didn't detect this.
* Writing those tests will be very complicated and means that you have to touch every part of the registration process of each container to verify whether such container is thread-safe. And you need to test all permutations of parallel registration options. This is close to impossible and means you need to do a thorough review of the code base of each container to know what and how to test. Take a look for instance at [this concurrency issue in Unity](https://unity.codeplex.com/workitem/12762) to get a feeling at how complicated it would be to detect all the edge cases of such API.
* Even if you write your concurrency tests based on the reviewed code base, this code base will change over time and this means that the concurrency tests need to evolve with that code base over time as well.
* It gets even more complex, because most containers allow their code to run on multiple processor architectures (x86, ARM) and they all have their own memory model. Code that is thread-safe on x86 isn't per definition thread-safe on ARM. I know this, because I did some special work on Simple Injector 2.0 to run on Mono and Windows Phone (ARM) and changes where made to make it thread-safe on weaker memory models. So if you are testing this, make sure those tests run on ARM as well, because this is probably where most the bugs will be.
* When doing this, you are actually doing the testing work that should be done by the library authors themselves. So you're not writing a feature test; you are writing the library's integration tests.

So instead of writing tests for this, it seems to me that this should be a simple documentation flag in the feature tests. Registration in a container is not thread-safe unless the container explicitly states it is. And if the container's documentation says it is thread-safe, this statement should be assumed to be accurate. Or at least, what this implies is that the intention of the maintainers is for their library to be thread-safe in that case, and their intention is to fix concurrency bugs if they are reported.

This documentation should also state which guarantees the container makes. For instance, can a made or changed registration influence a concurrently resolved object graph, or does a concurrent registration only influence resolves that happen after the registration succeeded? Or more practically, does making the registration block the resolve process until the registration is made. This can be a quite important difference that users should be aware of when doing registrations concurrently while resolved keep happening in parallel.

**Comment by asd-and-Rizzo** [comment]
Thanks for discussion. Some real container was tuned for better after. 
Will try to create some sound test/procedures of what if possible in some time of  future.

**Comment by ashmind** [comment]
I'm going to close this as I don't see a good way to do that at the moment.
Thanks to all for the input.
